{
  "YOUR_SKYBOX_DECAL_ID": "rbxassetid://102083691394047",
  "Name": "TargetButton",
  "TEST_SOUND_ID": "rbxassetid://126741080088368",
  "currentSound": null,
  "Text": "  ",
  "Volume": 1,
  "Looped": true,
  "i": 1,
  "BackgroundTransparency": 1,
  "TextScaled": true,
  "progress": 0,
  "IMAGE_ID": "rbxassetid://106331124875637",
  "AUDIO_ID": "rbxassetid://72495090165091",
  "currentScreenGui": null,
  "BorderSizePixel": 0,
  "ZIndex": 10,
  "connection": null,
  "ResetOnSpawn": false,
  "emojiCount": 0,
  "emojis": [
    "💀",
    "⚠️",
    "🚨",
    "❌",
    "🔥",
    "💥",
    "⚡",
    "🎮",
    "👻",
    "🤖",
    "😱",
    "🎯",
    "💢",
    "🚫",
    "🎪"
  ],
  "TextWrapped": true,
  "noclipEnabled": false,
  "noclipConnection": null,
  "CanCollide": true,
  "espEnabled": false,
  "espFolders": {
    "nested": "object (simplified)"
  },
  "AlwaysOnTop": true,
  "Enabled": true,
  "MaxDistance": 500,
  "Visible": false,
  "ScrollBarThickness": 6,
  "entries": {
    "nested": "object (simplified)"
  },
  "TextSize": 20,
  "Image": "rbxasset://textures/ui/GuiImagePlaceholder.png"
}
